# Eat Safe, Love

## Notebook Set Up

In [1]:
from pymongo import MongoClient
import pandas as pd
from pprint import pprint

In [2]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [3]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [4]:
# review the collections in our database
db.list_collection_names()

['establishments']

In [5]:
# assign the collection to a variable
establishments = db['establishments']

In [6]:
establishments.find_one()

{'_id': ObjectId('66a2b06e27493f4709a9ab01'),
 'FHRSID': 1043695,
 'ChangesByServerID': 0,
 'LocalAuthorityBusinessID': 'PI/000073616',
 'BusinessName': 'The Pavilion',
 'BusinessType': 'Restaurant/Cafe/Canteen',
 'BusinessTypeID': 1,
 'AddressLine1': 'East Cliff Pavilion',
 'AddressLine2': 'Wear Bay Road',
 'AddressLine3': 'Folkestone',
 'AddressLine4': 'Kent',
 'PostCode': 'CT19 6BL',
 'Phone': '',
 'RatingValue': 5,
 'RatingKey': 'fhrs_5_en-gb',
 'RatingDate': '2018-04-04T00:00:00',
 'LocalAuthorityCode': '188',
 'LocalAuthorityName': 'Folkestone and Hythe',
 'LocalAuthorityWebSite': 'http://www.folkestone-hythe.gov.uk',
 'LocalAuthorityEmailAddress': 'foodteam@folkestone-hythe.gov.uk',
 'scores': {'Hygiene': 5, 'Structural': 5, 'ConfidenceInManagement': 5},
 'SchemeType': 'FHRS',
 'geocode': {'longitude': '1.195625', 'latitude': '51.083812'},
 'RightToReply': '',
 'Distance': 4591.765489457773,
 'NewRatingPending': False,
 'meta': {'dataSource': None,
  'extractDate': '0001-01-01T00:00:00',
  'itemCount': 0,
  'returncode': None,
  'totalCount': 0,
  'totalPages': 0,
  'pageSize': 0,
  'pageNumber': 0},
 'links': [{'rel': 'self',
   'href': 'https://api.ratings.food.gov.uk/establishments/1043695'}],
 'longitude': None,
 'latitude': None}

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [7]:
# Find the establishments with a hygiene score of 20
query ={'scores.Hygiene':20}
result=establishments.find(query)
# Use count_documents to display the number of documents in the result
doc_count=establishments.count_documents(query)
# Display the first document in the results using pprint
pprint(result[0])

{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': 0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('66a2b06e27493f4709a9c634'),
 'geocode': {'latitude': '50.769705', 'longitude': '0.27694'},
 'latitude': None,
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [8]:
# Convert the result to a Pandas DataFrame
est_df=pd.DataFrame(result)
# Display the number of rows in the DataFrame
print(len(est_df))
# Display the first 10 rows of the DataFrame
est_df.head(10)

41

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links,longitude,latitude
0,66a2b06e27493f4709a9c634,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': '0.27694', 'latitude': '50.769705'}",,4613.888288,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
1,66a2b06e27493f4709a9c9b5,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': '1.278721', 'latitude': '51.8575...",,4617.965824,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
2,66a2b06e27493f4709a9ccc0,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': '1.15927', 'latitude': '51.789429'}",,4619.656144,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
3,66a2b06e27493f4709a9cead,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': '0.10202', 'latitude': '50.770885'}",,4620.421725,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
4,66a2b06e27493f4709a9cebb,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': '0.101446', 'latitude': '50.7707...",,4620.437179,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
5,66a2b06e27493f4709a9d85c,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': '0.736349', 'latitude': '51.5414...",,4625.565258,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
6,66a2b06e27493f4709a9da7b,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': '0.7121671', 'latitude': '51.535...",,4626.200132,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
7,66a2b06f27493f4709a9efa7,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': '0.602364', 'latitude': '51.5915...",,4632.276890,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
8,66a2b06f27493f4709a9f3ea,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,"{'Hygiene': 20, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': '0.146449998021126', 'latitude':...",,4633.934041,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
9,66a2b06f27493f4709a9fbfa,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': '0.462307', 'latitude': '51.57005'}",,4636.552523,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [9]:
#trick was using addressline2 instead of the Local Authority red herrings.
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query = {'AddressLine2': 'London','RatingValue': {'$gte': 4}}
result=establishments.find(query)
# Use count_documents to display the number of documents in the result
doc_count=establishments.count_documents(query)
# Display the first document in the results using pprint
pprint(result[0])

{'AddressLine1': 'Reeds River Cruises LtdKings ReachRiver ThamesSouthwark',
 'AddressLine2': 'London',
 'AddressLine3': '',
 'AddressLine4': '',
 'BusinessName': 'Mv Valulla',
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4640.460834256174,
 'FHRSID': 294900,
 'LocalAuthorityBusinessID': 'PI/000019066',
 'LocalAuthorityCode': '508',
 'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
 'LocalAuthorityName': 'City of London Corporation',
 'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'RM15 5QY',
 'RatingDate': '2016-08-23T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': 5,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('66a2b06f27493f4709aa03bc'),
 'geocode': {'latitude': '51.504071', 'longitude': '0.287555'},
 'latitude': None,
 'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/294900',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}}

In [10]:
# Convert the result to a Pandas DataFrame
est_df=pd.DataFrame(result)
# Display the number of rows in the DataFrame
print(len(est_df))
# Display the first 10 rows of the DataFrame
est_df.head(10)

99

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links,longitude,latitude
0,66a2b06f27493f4709aa03bc,294900,0,PI/000019066,Mv Valulla,Other catering premises,7841,Reeds River Cruises LtdKings ReachRiver Thames...,London,,...,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': '0.287555', 'latitude': '51.5040...",,4640.460834,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
1,66a2b06f27493f4709aa195a,1408389,0,21/00294/CP,Foodyz21,Restaurant/Cafe/Canteen,1,513 Abbey Road,London,,...,"{'Hygiene': 10, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': '0.121862', 'latitude': '51.48992'}",,4645.974290,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
2,66a2b06f27493f4709aa1971,1438466,0,22/00008/CP,Finest Chicken Peri Peri Grill,Takeaway/sandwich shop,7844,515 Abbey Road,London,,...,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': '0.121542', 'latitude': '51.4899...",,4645.986171,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
3,66a2b06f27493f4709aa1973,1156030,0,PI/000297297,Bona,Restaurant/Cafe/Canteen,1,25 Dartmouth Road,London,,...,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': '0.0143445', 'latitude': '51.383...",,4645.989753,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
4,66a2b06f27493f4709aa19f8,776404,0,15/00376/CP,Toddleswood Pre-School At Willowbank School,Caring Premises,5,Seacourt Road,London,,...,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': '0.125247', 'latitude': '51.4973...",,4646.124520,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
5,66a2b06f27493f4709aa19f9,930899,0,16/00266/CP,The Contract Dining Company At Willow Bank Pri...,School/college/university,7845,Seacourt Road,London,,...,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': '0.125247', 'latitude': '51.4973...",,4646.124520,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
6,66a2b06f27493f4709aa1a13,875250,0,14/00066/CP,The Ness Cafe,Restaurant/Cafe/Canteen,1,Belvedere Road,London,,...,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': '0.133478', 'latitude': '51.5060...",,4646.144584,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
7,66a2b06f27493f4709aa1a24,1064870,0,18/00191/CP,Turo Turo,Mobile caterer,7846,2 Portmeadow Walk,London,,...,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': '0.125036999583244', 'latitude':...",,4646.170654,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
8,66a2b06f27493f4709aa1ace,1223157,0,20/00040/CP,Falconwood Food & Wine,Retailers - other,4613,15 Lingfield Crescent,London,,...,"{'Hygiene': 0, 'Structural': 10, 'ConfidenceIn...",FHRS,"{'longitude': '0.08122', 'latitude': '51.45912'}",,4646.327301,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
9,66a2b06f27493f4709aa1acf,996676,0,17/00248/CP,Falcon News,Retailers - other,4613,1 Lingfield Crescent,London,,...,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': '0.0812200009822845', 'latitude'...",,4646.327364,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [23]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

degree_search = .01
latitude =51.49014200
longitude =0.08384000

query ={'RatingValue':5,'geocode.latitude':{'$gte':latitude-degree_search,'$lte':degree_search+latitude},
        'geocode.longitude':{'$gte':longitude-degree_search,'$lte':degree_search+longitude}}
sort = [('scores.Hygiene', 1)]
limit =5

# Print the results
pipeline=(query,sort,limit)
result=(list(establishments.find(query).sort(sort).limit(limit)))
pprint(result)

[{'AddressLine1': '130 - 132 Plumstead High Street',
  'AddressLine2': '',
  'AddressLine3': 'Plumstead',
  'AddressLine4': 'Greenwich',
  'BusinessName': 'Volunteer',
  'BusinessType': 'Pub/bar/nightclub',
  'BusinessTypeID': 7843,
  'ChangesByServerID': 0,
  'Distance': 4646.965634598608,
  'FHRSID': 694609,
  'LocalAuthorityBusinessID': 'PI/000116619',
  'LocalAuthorityCode': '511',
  'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
  'LocalAuthorityName': 'Greenwich',
  'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'SE18 1JQ',
  'RatingDate': '2019-08-05T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('66a2b06f27493f4709aa1e92'),
  'geocode': {'latitude': Decimal128('51.4873437'),
              'longitude': Decimal128('0.09208')},
  'latitude': None,
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/694609',
             'rel': 'self'}],
  'longitude': None,
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}},
 {'AddressLine1': 'Plumstead Manor School Old Mill Road',
  'AddressLine2': '',
  'AddressLine3': 'Plumstead',
  'AddressLine4': 'Greenwich',
  'BusinessName': 'Plumstead Manor Nursery',
  'BusinessType': 'Caring Premises',
  'BusinessTypeID': 5,
  'ChangesByServerID': 0,
  'Distance': 4646.9740101340385,
  'FHRSID': 695241,
  'LocalAuthorityBusinessID': 'PI/000179088',
  'LocalAuthorityCode': '511',
  'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
  'LocalAuthorityName': 'Greenwich',
  'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'SE18 1QG',
  'RatingDate': '2021-06-16T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('66a2b06f27493f4709aa1eab'),
  'geocode': {'latitude': Decimal128('51.481517791748'),
              'longitude': Decimal128('0.0859939977526665')},
  'latitude': None,
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/695241',
             'rel': 'self'}],
  'longitude': None,
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 0, 'Structural': 0}},
 {'AddressLine1': '35 Lakedale Road',
  'AddressLine2': '',
  'AddressLine3': 'Plumstead',
  'AddressLine4': 'Greenwich',
  'BusinessName': 'Atlantic Fish Bar',
  'BusinessType': 'Takeaway/sandwich shop',
  'BusinessTypeID': 7844,
  'ChangesByServerID': 0,
  'Distance': 4646.974611855838,
  'FHRSID': 694478,
  'LocalAuthorityBusinessID': 'PI/000086506',
  'LocalAuthorityCode': '511',
  'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
  'LocalAuthorityName': 'Greenwich',
  'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'SE18 1PR',
  'RatingDate': '2021-06-16T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('66a2b06f27493f4709aa1ead'),
  'geocode': {'latitude': Decimal128('51.4867296'),
              'longitude': Decimal128('0.0912164')},
  'latitude': None,
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/694478',
             'rel': 'self'}],
  'longitude': None,
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 0, 'Structural': 0}},
 {'AddressLine1': '144 - 146 Plumstead High Street',
  'AddressLine2': '',
  'AddressLine3': 'Plumstead',
  'AddressLine4': 'Greenwich',
  'BusinessName': 'Iceland',
  'BusinessType': 'Retailers - supermarkets/hypermarkets',
  'BusinessTypeID': 7840,
  'ChangesByServerID': 0,
  'Distance': 4646.946071297699,
  'FHRSID': 695223,
  'LocalAuthorityBusinessID': 'PI/000178842',
  'LocalAuthorityCode': '511',
  'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
  'LocalAuthorityName': 'Greenwich',
  'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'SE18 1JQ',
  'RatingDate': '2019-11-13T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('66a2b06f27493f4709aa1e65'),
  'geocode': {'latitude': Decimal128('51.4871482849121'),
              'longitude': Decimal128('0.0924199968576431')},
  'latitude': None,
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/695223',
             'rel': 'self'}],
  'longitude': None,
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 0, 'Structural': 5}},
 {'AddressLine1': 'Restaurant And Premises 107A Plumstead High Street',
  'AddressLine2': '',
  'AddressLine3': 'Plumstead',
  'AddressLine4': 'Greenwich',
  'BusinessName': 'Howe and Co Fish and Chips - Van 17',
  'BusinessType': 'Mobile caterer',
  'BusinessTypeID': 7846,
  'ChangesByServerID': 0,
  'Distance': 4646.95593107927,
  'FHRSID': 1380578,
  'LocalAuthorityBusinessID': '14425',
  'LocalAuthorityCode': '511',
  'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
  'LocalAuthorityName': 'Greenwich',
  'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'SE18 1SE',
  'RatingDate': '2021-11-11T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('66a2b06f27493f4709aa1e78'),
  'geocode': {'latitude': Decimal128('51.4875335693359'),
              'longitude': Decimal128('0.0925370007753372')},
  'latitude': None,
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/1380578',
             'rel': 'self'}],
  'longitude': None,
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}}]

In [26]:
# Convert result to Pandas DataFrame
hygiene_score_df=pd.DataFrame(result)
hygiene_score_df

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links,longitude,latitude
0,66a2b06f27493f4709aa1e92,694609,0,PI/000116619,Volunteer,Pub/bar/nightclub,7843,130 - 132 Plumstead High Street,,Plumstead,...,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.09208, 'latitude': 51.4873437}",,4646.965635,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
1,66a2b06f27493f4709aa1eab,695241,0,PI/000179088,Plumstead Manor Nursery,Caring Premises,5,Plumstead Manor School Old Mill Road,,Plumstead,...,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.0859939977526665, 'latitude': ...",,4646.974010,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
2,66a2b06f27493f4709aa1ead,694478,0,PI/000086506,Atlantic Fish Bar,Takeaway/sandwich shop,7844,35 Lakedale Road,,Plumstead,...,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.0912164, 'latitude': 51.4867296}",,4646.974612,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
3,66a2b06f27493f4709aa1e65,695223,0,PI/000178842,Iceland,Retailers - supermarkets/hypermarkets,7840,144 - 146 Plumstead High Street,,Plumstead,...,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.0924199968576431, 'latitude': ...",,4646.946071,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
4,66a2b06f27493f4709aa1e78,1380578,0,14425,Howe and Co Fish and Chips - Van 17,Mobile caterer,7846,Restaurant And Premises 107A Plumstead High St...,,Plumstead,...,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.0925370007753372, 'latitude': ...",,4646.955931,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [30]:
# Create a pipeline that:
# 1. Matches establishments with a hygiene score of 0
# 2. Groups the matches by Local Authority
# 3. Sorts the matches from highest to lowest
query_match={'$match':{'scores.Hygiene':0}}
group_match={'$group':{'_id':'$LocalAuthorityName','count':{'$sum':1}}}
sort={'$sort':{'count':-1}}
# Print the number of documents in the result
pipeline=[query_match,group_match,sort]
results=list(establishments.aggregate(pipeline))
print("Number of documents in result:",len(results))
# Print the first 10 results
pprint(list(results[:10]))

Number of documents in result: 55
[{'_id': 'Thanet', 'count': 1130},
 {'_id': 'Greenwich', 'count': 882},
 {'_id': 'Maidstone', 'count': 713},
 {'_id': 'Newham', 'count': 711},
 {'_id': 'Swale', 'count': 686},
 {'_id': 'Chelmsford', 'count': 680},
 {'_id': 'Medway', 'count': 672},
 {'_id': 'Bexley', 'count': 607},
 {'_id': 'Southend-On-Sea', 'count': 586},
 {'_id': 'Tendring', 'count': 542}]

In [33]:
# Convert the result to a Pandas DataFrame
result_df=pd.DataFrame(results)
# Display the number of rows in the DataFrame
print(len(result_df))
# Display the first 10 rows of the DataFrame
result_df.head(10)

55

               _id  count
0           Thanet   1130
1        Greenwich    882
2        Maidstone    713
3           Newham    711
4            Swale    686
5       Chelmsford    680
6           Medway    672
7           Bexley    607
8  Southend-On-Sea    586
9         Tendring    542